/**
 * cards/deck.standard.ts ─ 标准版牌堆逐张数据(108 张,含 4 张 EX)。
 * 内容与 docs/data/standard-deck.md §7 的 JSON 完全一致(由脚本原样转换,保留 zh 与 extra);
 * 下标即 CardId。过滤 extra.ex === true 的 4 条即为 104 张版本。
 */
import type { DeckEntry } from '../core/types.js'

/** 标准版 108 张牌,顺序与 docs/data/standard-deck.md §7 一致 */
export const STANDARD_DECK: readonly DeckEntry[] = [
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 7 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 8 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 8 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 9 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 9 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'spade', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'heart', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'heart', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'heart', rank: 11 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 2 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 3 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 4 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 5 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 6 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 7 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 8 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 8 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 9 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 9 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 11 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'club', rank: 11 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 6 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 7 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 8 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 9 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 10 },
  { name: 'slash', zh: '杀', kind: 'basic', suit: 'diamond', rank: 13 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'heart', rank: 2 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'heart', rank: 2 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'heart', rank: 13 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 2 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 2 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 3 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 4 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 5 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 6 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 7 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 8 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 9 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 10 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 11 },
  { name: 'jink', zh: '闪', kind: 'basic', suit: 'diamond', rank: 11 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 3 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 4 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 6 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 7 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 8 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 9 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'heart', rank: 12 },
  { name: 'peach', zh: '桃', kind: 'basic', suit: 'diamond', rank: 12 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'spade', rank: 3 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'spade', rank: 4 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'spade', rank: 12 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'heart', rank: 12 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'club', rank: 3 },
  { name: 'dismantlement', zh: '过河拆桥', kind: 'trick', suit: 'club', rank: 4 },
  { name: 'snatch', zh: '顺手牵羊', kind: 'trick', suit: 'spade', rank: 3 },
  { name: 'snatch', zh: '顺手牵羊', kind: 'trick', suit: 'spade', rank: 4 },
  { name: 'snatch', zh: '顺手牵羊', kind: 'trick', suit: 'spade', rank: 11 },
  { name: 'snatch', zh: '顺手牵羊', kind: 'trick', suit: 'diamond', rank: 3 },
  { name: 'snatch', zh: '顺手牵羊', kind: 'trick', suit: 'diamond', rank: 4 },
  { name: 'duel', zh: '决斗', kind: 'trick', suit: 'spade', rank: 1 },
  { name: 'duel', zh: '决斗', kind: 'trick', suit: 'club', rank: 1 },
  { name: 'duel', zh: '决斗', kind: 'trick', suit: 'diamond', rank: 1 },
  { name: 'collateral', zh: '借刀杀人', kind: 'trick', suit: 'club', rank: 12 },
  { name: 'collateral', zh: '借刀杀人', kind: 'trick', suit: 'club', rank: 13 },
  { name: 'ex_nihilo', zh: '无中生有', kind: 'trick', suit: 'heart', rank: 7 },
  { name: 'ex_nihilo', zh: '无中生有', kind: 'trick', suit: 'heart', rank: 8 },
  { name: 'ex_nihilo', zh: '无中生有', kind: 'trick', suit: 'heart', rank: 9 },
  { name: 'ex_nihilo', zh: '无中生有', kind: 'trick', suit: 'heart', rank: 11 },
  { name: 'nullification', zh: '无懈可击', kind: 'trick', suit: 'spade', rank: 11 },
  { name: 'nullification', zh: '无懈可击', kind: 'trick', suit: 'club', rank: 12 },
  { name: 'nullification', zh: '无懈可击', kind: 'trick', suit: 'club', rank: 13 },
  {
    name: 'nullification',
    zh: '无懈可击',
    kind: 'trick',
    suit: 'diamond',
    rank: 12,
    extra: { ex: true },
  },
  { name: 'savage_assault', zh: '南蛮入侵', kind: 'trick', suit: 'spade', rank: 7 },
  { name: 'savage_assault', zh: '南蛮入侵', kind: 'trick', suit: 'spade', rank: 13 },
  { name: 'savage_assault', zh: '南蛮入侵', kind: 'trick', suit: 'club', rank: 7 },
  { name: 'archery_attack', zh: '万箭齐发', kind: 'trick', suit: 'heart', rank: 1 },
  { name: 'peach_garden', zh: '桃园结义', kind: 'trick', suit: 'heart', rank: 1 },
  { name: 'amazing_grace', zh: '五谷丰登', kind: 'trick', suit: 'heart', rank: 3 },
  { name: 'amazing_grace', zh: '五谷丰登', kind: 'trick', suit: 'heart', rank: 4 },
  { name: 'indulgence', zh: '乐不思蜀', kind: 'delayed_trick', suit: 'spade', rank: 6 },
  { name: 'indulgence', zh: '乐不思蜀', kind: 'delayed_trick', suit: 'heart', rank: 6 },
  { name: 'indulgence', zh: '乐不思蜀', kind: 'delayed_trick', suit: 'club', rank: 6 },
  { name: 'lightning', zh: '闪电', kind: 'delayed_trick', suit: 'spade', rank: 1 },
  {
    name: 'lightning',
    zh: '闪电',
    kind: 'delayed_trick',
    suit: 'heart',
    rank: 12,
    extra: { ex: true },
  },
  { name: 'crossbow', zh: '诸葛连弩', kind: 'weapon', suit: 'club', rank: 1, extra: { range: 1 } },
  {
    name: 'crossbow',
    zh: '诸葛连弩',
    kind: 'weapon',
    suit: 'diamond',
    rank: 1,
    extra: { range: 1 },
  },
  {
    name: 'qinggang_sword',
    zh: '青釭剑',
    kind: 'weapon',
    suit: 'spade',
    rank: 6,
    extra: { range: 2 },
  },
  {
    name: 'ice_sword',
    zh: '寒冰剑',
    kind: 'weapon',
    suit: 'spade',
    rank: 2,
    extra: { range: 2, ex: true },
  },
  {
    name: 'double_swords',
    zh: '雌雄双股剑',
    kind: 'weapon',
    suit: 'spade',
    rank: 2,
    extra: { range: 2 },
  },
  { name: 'blade', zh: '青龙偃月刀', kind: 'weapon', suit: 'spade', rank: 5, extra: { range: 3 } },
  { name: 'spear', zh: '丈八蛇矛', kind: 'weapon', suit: 'spade', rank: 12, extra: { range: 3 } },
  { name: 'axe', zh: '贯石斧', kind: 'weapon', suit: 'diamond', rank: 5, extra: { range: 3 } },
  {
    name: 'halberd',
    zh: '方天画戟',
    kind: 'weapon',
    suit: 'diamond',
    rank: 12,
    extra: { range: 4 },
  },
  { name: 'kylin_bow', zh: '麒麟弓', kind: 'weapon', suit: 'heart', rank: 5, extra: { range: 5 } },
  { name: 'eight_diagram', zh: '八卦阵', kind: 'armor', suit: 'spade', rank: 2 },
  { name: 'eight_diagram', zh: '八卦阵', kind: 'armor', suit: 'club', rank: 2 },
  {
    name: 'renwang_shield',
    zh: '仁王盾',
    kind: 'armor',
    suit: 'club',
    rank: 2,
    extra: { ex: true },
  },
  {
    name: 'chitu',
    zh: '赤兔',
    kind: 'horse_offensive',
    suit: 'heart',
    rank: 5,
    extra: { distance: -1 },
  },
  {
    name: 'dayuan',
    zh: '大宛',
    kind: 'horse_offensive',
    suit: 'spade',
    rank: 13,
    extra: { distance: -1 },
  },
  {
    name: 'zixing',
    zh: '紫骍',
    kind: 'horse_offensive',
    suit: 'diamond',
    rank: 13,
    extra: { distance: -1 },
  },
  {
    name: 'dilu',
    zh: '的卢',
    kind: 'horse_defensive',
    suit: 'club',
    rank: 5,
    extra: { distance: 1 },
  },
  {
    name: 'jueying',
    zh: '绝影',
    kind: 'horse_defensive',
    suit: 'spade',
    rank: 5,
    extra: { distance: 1 },
  },
  {
    name: 'zhuahuangfeidian',
    zh: '爪黄飞电',
    kind: 'horse_defensive',
    suit: 'heart',
    rank: 13,
    extra: { distance: 1 },
  },
]
